/**
 * The contract between this page and the pipeline that feeds it.
 *
 * `index.json` in this directory is generated by the private `publicai-index`
 * repository and delivered by pull request. Nothing in this app writes it.
 * These types are the schema that file must satisfy; the pipeline's own tests
 * validate against the same shape.
 *
 * Scores belong to their publishers. PublicAI normalizes and weights them; it
 * does not run these benchmarks.
 */

/** How a source reports its numbers. Drives normalization, not display. */
export type Metric = 'elo' | 'percent' | 'index';

/**
 * Where a figure comes from.
 *
 * - `board`: a leaderboard PublicAI recognises — a maintained, first-party
 *   ranking page. Shown without a mark.
 * - `report`: a one-off publication — a vendor's launch post, a lab's blog,
 *   an evaluator's write-up. Shown with a ✱. Never enters the Overall index
 *   and never counts toward ranking eligibility; widens the domain columns.
 */
export type SourceKind = 'board' | 'report';

export interface Benchmark {
  id: string;
  name: string;
  publisher: string;
  /** The exact page the numbers were read from. Rendered as the citation. */
  url: string;
  /** ISO date the figures were read. */
  retrievedAt: string;
  /** The leaderboard's own snapshot label, where it publishes one. */
  snapshot?: string;
  /** For reports: the date the publication is dated. */
  publishedAt?: string;
  /**
   * False when the publisher was measuring its own model. Optional because
   * snapshots written before the field existed do not carry it; absent reads
   * as "not independent", which is the conservative way to be wrong.
   */
  independent?: boolean;
  metric: Metric;
  /** Top-level capability area. Fixed vocabulary. */
  category: string;
  /** The specific capability this number is evidence of. */
  domain: string;
  /** Known limitation a buyer should weigh before trusting the column. */
  caveat?: string;
  kind: SourceKind;
  /** Display name of the source this measure belongs to. Boards repeat their headline name; reports carry the publication's title. */
  source: string;
  /**
   * The source this measure belongs to, by id. LiveBench's category figures
   * all point at `livebench`; single-measure boards point at themselves; a
   * report's measures all point at the report. Coverage counts sources.
   */
  group: string;
}

export interface Score {
  modelId: string;
  benchmarkId: string;
  raw: number;
  /** Published uncertainty, where the source reports one. Drives confidence weighting. */
  stderr?: number;
  /** The model string exactly as that source prints it. Shown in provenance. */
  sourceLabel: string;
  /** Agent framework the score was produced with, where the source scores a scaffold. */
  scaffold?: string;
}

/** Where a model is listed on OpenRouter: one OpenAI-compatible endpoint, one id, for many vendors. */
export interface AccessOpenRouter {
  id: string;
  url: string;
  contextLength?: number;
  /** USD per million tokens at the date read; absent where the router prints a variable price. */
  inputPerM?: number;
  outputPerM?: number;
  /** ISO date the router first listed the model. */
  listedAt?: string;
  modalities?: string[];
}

/**
 * How a model can be reached. None of this touches a score; it is carried so
 * an answer to "which model?" can also say "and here is how to call it".
 */
export interface Access {
  openrouter?: AccessOpenRouter;
  /** Open weights, where the catalog links a repository. */
  weights?: { huggingFaceId: string; url: string };
  /** The vendor's own developer site. Curated per organisation, not read from a source. */
  official?: { name: string; url: string };
}

/** Parameter count, where one is known. Closed models have none; nothing is estimated. */
export interface Size {
  /** Total parameters, in billions. */
  paramsB: number;
  /** Active parameters per token on a mixture-of-experts, in billions. */
  activeB?: number;
  /** `huggingface`: counted from the weights files. `name`: read from the model's own name. */
  source: 'huggingface' | 'name';
}

export interface Model {
  id: string;
  name: string;
  org: string;
  access?: Access;
  size?: Size;
}

/** A catalog the access fields were read from. Cited like a board, never scored. */
export interface Catalog {
  id: string;
  name: string;
  publisher: string;
  url: string;
  retrievedAt: string;
  caveat?: string;
}

/** A well-known board deliberately left out, and why. Exclusions are part of the method. */
export interface Excluded {
  name: string;
  url: string;
  reason: string;
}

export interface IndexData {
  /** ISO timestamp of the pipeline run that produced this file. */
  generatedAt: string;
  benchmarks: Benchmark[];
  models: Model[];
  scores: Score[];
  excluded: Excluded[];
  catalogs: Catalog[];
}
