/**
 * The contract between this page and the pipeline that feeds it.
 *
 * `index.json` in this directory is generated by the private `publicai-index`
 * repository and delivered by pull request. Nothing in this app writes it.
 * These types are the schema that file must satisfy; the pipeline's own tests
 * validate against the same shape.
 *
 * Scores belong to their publishers. PublicAI normalizes and weights them; it
 * does not run these benchmarks.
 */

/** How a leaderboard reports its numbers. Drives normalization, not display. */
export type Metric = 'elo' | 'percent' | 'index';

export interface Benchmark {
  id: string;
  name: string;
  publisher: string;
  /** The exact page the numbers were read from. Rendered as the citation. */
  url: string;
  /** ISO date the figures were read. */
  retrievedAt: string;
  /** The leaderboard's own snapshot label, where it publishes one. */
  snapshot?: string;
  metric: Metric;
  /** What capability this leaderboard actually measures. */
  domain: string;
  /** Known limitation a buyer should weigh before trusting the column. */
  caveat?: string;
}

export interface Score {
  modelId: string;
  benchmarkId: string;
  raw: number;
  /** Published uncertainty, where the leaderboard reports one. Drives confidence weighting. */
  stderr?: number;
  /** The model string exactly as that leaderboard prints it. Shown in provenance. */
  sourceLabel: string;
  /** Agent framework the score was produced with, where the benchmark scores a scaffold rather than a bare model. */
  scaffold?: string;
}

export interface Model {
  id: string;
  name: string;
  org: string;
}

/** A well-known board deliberately left out, and why. Exclusions are part of the method. */
export interface Excluded {
  name: string;
  url: string;
  reason: string;
}

export interface IndexData {
  /** ISO timestamp of the pipeline run that produced this file. */
  generatedAt: string;
  benchmarks: Benchmark[];
  models: Model[];
  scores: Score[];
  excluded: Excluded[];
}
